[workspace] # ESNODE | Source Available BUSL-1.1 | Copyright (c) 2025 Estimatedstocks AB
resolver = "2"
members = [
    "crates/agent-core",
    "crates/agent-bin",
    "ESNODE-Orchestrator", "crates/esnode-modbus", "crates/esnode-dnp3", "crates/esnode-snmp", "crates/esnode-mqtt",
]
